version: '3'
services:
  user-app:
    image: user-app
    build: MovieCruiserAuthenticationService/
    restart: always
    network_mode: host
    ports:
      - 8080:8080
    expose:
      - 8089
    depends_on:
      - movie-mysql
  movie-app:
    image: movie-app
    build: MovieCruiserServerApplication/
    restart: always
    network_mode: host
    ports:
      - 8020:8082
    expose:
      - 8082
    depends_on:
      - movie-mysql
  movie-mysql:
   image: mysql:5.5
   ports:
     - 3306:3306
   network_mode: host
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: moviedb
     MYSQL_USER: app_root
     MYSQL_PASSWORD: root



