spring:
  datasource:
    url: ${MYSQL_CI_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true   
server:
  port: 8089
  
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/moviedb
#    username: root
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true    
#server:
#  port: 8089
    